#!/usr/bin/env bash
set -euo pipefail
source /usr/local/lib/dragonshark-bluetooth-utils

# 1. First, prepare the bluetooth drivers.
ensure_bluetooth_up

# 2. List all the paired devices and format them accordingly.
bluetoothctl paired-devices | awk '
  $1=="Device"{
    mac=$2;
    $1=""; $2="";
    sub(/^  /,"");
    name=$0;
    printf "%s\t%s\n", mac, name
  }
' || true

# The result goes via stdout. Each entry is: "<mac><tab><name>",
# considering the name has no spaces. It serves to be parsed
# by a tools breaking by tabs and having two entries.
