#!/bin/bash

# Sets the Master volume
if [[ "$1" =~ ^[0-9]+$ ]] && [ "$1" -ge 0 ] && [ "$1" -le 100 ]; then
    amixer set Master "$1"% > /dev/null
    echo "Volume set to $1%"
else
    echo "Invalid volume value. Please specify a number between 0 and 100." 1>&2
    exit 1
fi