#!/usr/bin/env bash
set -euo pipefail
source /usr/local/lib/dragonshark-bluetooth-utils

# Args: <device name or mac> <time>

# 1. First, prepare the bluetooth drivers.
ensure_bluetooth_up

# 2. Get the chosen device's mac. A failure
#    here results in a failure of this command.
mac="$(resolve_device_to_mac "${1:-}" "${2:-6}")"

# 3. Pair, trust and connect the device. This is done in
#    an interactive session since bluez in Armbian has some
#    issues. The store_hint=1 is never set if the commands
#    are non-interactive, so [LinkKeys] are never stored
#    and then the pairing is lost when the device is turned
#    off / disconnected. And a timing of 3 seconds between
#    commands is also useful here.
(
  echo "pair $mac"
  sleep 3
  echo "trust $mac"
  sleep 3
  echo "connect $max"
) | bluetoothctl
# bluetoothctl pair "$mac"
# bluetoothctl trust "$mac"
# bluetoothctl connect "$mac"
echo "paired successfully: $mac"

# The result is only the code. No stdout is meaningful.
