#!/usr/bin/env bash
set -euo pipefail
source /usr/local/lib/dragonshark-bluetooth-utils

# Args: <device name or mac> <time>

# 1. First, prepare the bluetooth drivers.
ensure_bluetooth_up

# 2. Get the chosen device's mac. A failure
#    here results in a failure of this command.
mac="$(resolve_device_to_mac "${1:-}" "${2:-6}")"

# 3. Pair, trust and connect the device.
(
  echo "pair $mac"
  sleep 3
  echo "trust $mac"
  sleep 3
  echo "connect $max"
) | bluetoothctl
# bluetoothctl pair "$mac"
# bluetoothctl trust "$mac"
# bluetoothctl connect "$mac"
echo "paired successfully: $mac"

# The result is only the code. No stdout is meaningful.
