#!/bin/bash

# Gets the new ROMs directory.
DIR=$(cat ~/.emulationstation/es_systems.cfg | grep -Po "<path>\K.*(?=</path>)" | head -n 1)
if [[ $? -ne 0 ]]
then
    echo "Could not retrieve the current ROMs directory" 1>&2
    exit 1
fi
echo $(dirname $DIR)